"""
utils/report_generator.py
==========================
Generates a downloadable PDF report of the resume analysis.
Uses ReportLab's Platypus framework for structured, multi-page PDFs.

The report includes:
- ATS score summary
- Matched & missing skills
- Improvement suggestions
- Learning roadmap
"""

import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether,
)
from reportlab.lib.colors import HexColor, Color
from utils.ats_scoring import calculate_ats_score
# ── Color Palette ─────────────────────────────────────────────────────────────
C_BLACK      = HexColor("#0d0d0d")
C_DARK       = HexColor("#141414")
C_CARD       = HexColor("#ffffff")
C_BORDER     = HexColor("#d1d5db")
C_TEXT       = HexColor("#111827")
C_SECONDARY  = HexColor("#4B5563")
C_GREEN      = HexColor("#22c55e")
C_RED        = HexColor("#ef4444")
C_AMBER      = HexColor("#f59e0b")
C_BLUE       = HexColor("#3b82f6")
C_PURPLE     = HexColor("#a78bfa")
C_WHITE      = HexColor("#ffffff")


def _score_color(score: int) -> Color:
    if score >= 70:
        return C_GREEN
    if score >= 50:
        return C_AMBER
    return C_RED

def generate_pdf_report(analysis: dict, resume_text: str, job_description: str) -> bytes:
    """
    Generate a complete PDF analysis report.

    Args:
        analysis:        Dict returned by analyze_resume()
        resume_text:     Original resume text (for reference)
        job_description: Original JD text (for reference)

    Returns:
        PDF as bytes (suitable for st.download_button)
    """
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20*mm,
        rightMargin=20*mm,
        topMargin=18*mm,
        bottomMargin=18*mm,
        title="Resume Analysis Report",
        author="AI Resume Analyzer",
    )

    styles = _build_styles()
    story  = []

    # ── COVER / HEADER ──────────────────────────────────────────────────────
    story.extend(_build_header(styles, analysis))

    # ── ATS SCORE SECTION ───────────────────────────────────────────────────
    story.extend(_build_ats_section(styles, analysis))

    # ── SKILL BREAKDOWN ─────────────────────────────────────────────────────
    story.extend(_build_skills_section(styles, analysis))

    # ── STRENGTHS ───────────────────────────────────────────────────────────
    story.extend(_build_strengths_section(styles, analysis))

    # ── IMPROVEMENT SUGGESTIONS ─────────────────────────────────────────────
    story.extend(_build_suggestions_section(styles, analysis))

    # ── LEARNING ROADMAP ────────────────────────────────────────────────────
    story.extend(_build_roadmap_section(styles, analysis))

    # ── FOOTER NOTE ─────────────────────────────────────────────────────────
    story.append(Spacer(1, 8*mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_BORDER))
    story.append(Spacer(1, 3*mm))
    story.append(Paragraph(
        f"Generated by AI Resume Analyzer · {datetime.now().strftime('%B %d, %Y at %H:%M')}",
        styles["footer"]
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()


# ══════════════════════════════════════════════════════════════════════════════
# STYLE DEFINITIONS
# ══════════════════════════════════════════════════════════════════════════════
def _build_styles() -> dict:
    base = getSampleStyleSheet()

    def make(name, **kwargs):
        return ParagraphStyle(name=name, **kwargs)

    return {
        "report_title": make("report_title",
            fontSize=22, textColor=C_TEXT, fontName="Helvetica-Bold",
            spaceAfter=2*mm, spaceBefore=0, leading=26,
        ),
        "report_subtitle": make("report_subtitle",
            fontSize=9, textColor=C_SECONDARY, fontName="Helvetica",
            spaceAfter=6*mm, leading=14,
        ),
        "section_header": make("section_header",
            fontSize=11, textColor=C_TEXT, fontName="Helvetica-Bold",
            spaceBefore=5*mm, spaceAfter=3*mm, leading=16,
            borderPad=0,
        ),
        "body": make("body",
            fontSize=9, textColor=C_SECONDARY, fontName="Helvetica",
            spaceAfter=2*mm, leading=14,
        ),
        "body_white": make("body_white",
            fontSize=9, textColor=C_TEXT, fontName="Helvetica",
            spaceAfter=2*mm, leading=14,
        ),
        "badge": make("badge",
            fontSize=8, textColor=C_SECONDARY, fontName="Helvetica",
            spaceAfter=0, leading=12,
        ),
        "bullet": make("bullet",
            fontSize=9, textColor=C_SECONDARY, fontName="Helvetica",
            bulletIndent=10, leftIndent=18, spaceAfter=2*mm, leading=14,
            bulletText="•",
        ),
        "week_header": make("week_header",
            fontSize=10, textColor=C_TEXT, fontName="Helvetica-Bold",
            spaceBefore=4*mm, spaceAfter=1*mm, leading=14,
        ),
        "footer": make("footer",
            fontSize=7.5, textColor=C_SECONDARY, fontName="Helvetica",
            alignment=TA_CENTER, spaceAfter=0, leading=12,
        ),
        "mono": make("mono",
            fontSize=8, textColor=C_SECONDARY, fontName="Courier",
            spaceAfter=0, leading=12,
        ),
    }


# ══════════════════════════════════════════════════════════════════════════════
# SECTION BUILDERS
# ══════════════════════════════════════════════════════════════════════════════
def _build_header(styles, analysis) -> list:
    items = []
    date_str = datetime.now().strftime("%B %d, %Y")

    # Title block
    items.append(Paragraph("Resume Analysis Report", styles["report_title"]))
    items.append(Paragraph(
        f"Powered by Gemini AI  ·  {date_str}",
        styles["report_subtitle"],
    ))
    items.append(HRFlowable(width="100%", thickness=0.5, color=C_BORDER))
    items.append(Spacer(1, 4*mm))
    return items


def _build_ats_section(styles, analysis) -> list:
    items = []
    score = calculate_ats_score(analysis)
    color = _score_color(score)
    label = "Strong Match" if score >= 70 else "Moderate Match" if score >= 50 else "Needs Improvement"
    summary = analysis.get("ats_summary", "")

    items.append(Paragraph("ATS COMPATIBILITY SCORE", styles["section_header"]))

    # Score table
    score_table = Table(
        [[
            Paragraph(f"<font size='36' color='{color.hexval()}'><b>{score}%</b></font>", styles["body_white"]),
            Paragraph(
                f"<b>{label}</b><br/><br/>{summary}",
                styles["body_white"]
            ),
        ]],
        colWidths=["30%", "70%"],
    )
    score_table.setStyle(TableStyle([
        ("BACKGROUND",  (0,0), (-1,-1), C_CARD),
        ("ROUNDEDCORNERS", [4]),
        ("BOX",         (0,0), (-1,-1), 0.5, C_BORDER),
        ("VALIGN",      (0,0), (-1,-1), "MIDDLE"),
        ("LEFTPADDING", (0,0), (-1,-1), 10),
        ("RIGHTPADDING",(0,0), (-1,-1), 10),
        ("TOPPADDING",  (0,0), (-1,-1), 8),
        ("BOTTOMPADDING",(0,0),(-1,-1), 8),
    ]))
    items.append(score_table)
    items.append(Spacer(1, 4*mm))
    return items


def _build_skills_section(styles, analysis) -> list:
    items = []
    matched = analysis.get("matched_skills", [])
    missing = analysis.get("missing_skills", [])

    items.append(Paragraph("SKILL BREAKDOWN", styles["section_header"]))

    matched_text = ", ".join(matched) if matched else "None identified"
    missing_text = ", ".join(missing) if missing else "None — great match!"

    skill_data = [
        [
            Paragraph("<b>✓ MATCHED SKILLS</b>", ParagraphStyle("sh", fontSize=9, textColor=C_GREEN, fontName="Helvetica-Bold")),
            Paragraph("<b>✗ MISSING SKILLS</b>", ParagraphStyle("sh2", fontSize=9, textColor=C_RED, fontName="Helvetica-Bold")),
        ],
        [
            Paragraph(matched_text, styles["body_white"]),
            Paragraph(missing_text, styles["body_white"]),
        ]
    ]

    skill_table = Table(skill_data, colWidths=["50%", "50%"])
    skill_table.setStyle(TableStyle([
        ("BACKGROUND",   (0,0), (-1,0), HexColor("#f3f4f6")),
        ("BACKGROUND",   (0,1), (-1,1), C_CARD),
        ("BOX",          (0,0), (-1,-1), 1, C_BORDER),
        ("INNERGRID",    (0,0), (-1,-1), 0.5, C_BORDER),
        ("LEFTPADDING",  (0,0), (-1,-1), 8),
        ("RIGHTPADDING", (0,0), (-1,-1), 8),
        ("TOPPADDING",   (0,0), (-1,-1), 6),
        ("BOTTOMPADDING",(0,0), (-1,-1), 6),
        ("VALIGN",       (0,0), (-1,-1), "TOP"),
    ]))
    items.append(skill_table)

    # Missing skills detail table
    detail = analysis.get("missing_skills_detail", [])
    if detail:
        items.append(Spacer(1, 4*mm))
        items.append(Paragraph("MISSING SKILLS — PRIORITY BREAKDOWN", styles["section_header"]))

        from typing import Any
        table_data: list[list[Any]] = [
           ["Skill", "Category", "Priority", "Why It Matters"]
        ]
        for row in detail:
            priority = row.get("priority", "Medium")
            pcolor = {"High": "#ef4444", "Medium": "#f59e0b", "Low": "#22c55e"}.get(priority, "#9a9a9a")
            table_data.append([
                Paragraph(row.get("skill", ""), styles["body_white"]),
                Paragraph(row.get("category", ""), styles["badge"]),
                Paragraph(f"<font color='{pcolor}'><b>{priority}</b></font>", styles["badge"]),
                Paragraph(row.get("why_important", ""), styles["body"]),
            ])

        detail_table = Table(table_data, colWidths=["20%", "18%", "12%", "50%"])
        detail_table.setStyle(TableStyle([
            ("BACKGROUND",   (0,0), (-1,0), HexColor("#f3f4f6")),
            ("TEXTCOLOR",    (0,0), (-1,0), C_TEXT),
            ("FONTNAME",     (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE",     (0,0), (-1,0), 8),
            ("BACKGROUND",   (0,1), (-1,-1), C_CARD),
            ("ROWBACKGROUNDS",(0,1),(-1,-1), [colors.white, HexColor("#f9fafb")]),
            ("BOX",          (0,0), (-1,-1), 1, C_BORDER),
            ("INNERGRID",    (0,0), (-1,-1), 0.3, C_BORDER),
            ("LEFTPADDING",  (0,0), (-1,-1), 6),
            ("RIGHTPADDING", (0,0), (-1,-1), 6),
            ("TOPPADDING",   (0,0), (-1,-1), 5),
            ("BOTTOMPADDING",(0,0), (-1,-1), 5),
            ("VALIGN",       (0,0), (-1,-1), "TOP"),
        ]))
        items.append(detail_table)

    items.append(Spacer(1, 3*mm))
    return items


def _build_strengths_section(styles, analysis) -> list:
    items = []
    strengths = analysis.get("strengths", [])
    if not strengths:
        return items

    items.append(Paragraph("RESUME STRENGTHS", styles["section_header"]))
    for s in strengths:
        items.append(Paragraph(f"⚡  {s}", styles["bullet"]))
    items.append(Spacer(1, 2*mm))
    return items


def _build_suggestions_section(styles, analysis) -> list:
    items = []
    suggestions = analysis.get("improvement_suggestions", [])
    if not suggestions:
        return items

    items.append(Paragraph("IMPROVEMENT SUGGESTIONS", styles["section_header"]))
    for i, s in enumerate(suggestions, 1):
        items.append(Paragraph(f"{i:02d}.  {s}", styles["bullet"]))
    items.append(Spacer(1, 2*mm))
    return items


def _build_roadmap_section(styles, analysis) -> list:
    items = []
    roadmap = analysis.get("learning_roadmap", [])
    if not roadmap:
        return items

    items.append(Paragraph("PERSONALIZED LEARNING ROADMAP (8 WEEKS)", styles["section_header"]))
    items.append(Paragraph(
        "A structured plan based on your skill gaps, prioritizing high-impact skills first.",
        styles["body"],
    ))
    items.append(Spacer(1, 3*mm))

    for week_data in roadmap:
        week_num  = week_data.get("week", "")
        topic     = week_data.get("topic", "")
        goal      = week_data.get("goal", "")
        resources = week_data.get("resources", [])

        from typing import Any
        week_block: list[Any] = [
            Paragraph(f"Week {week_num} — {topic}", styles["week_header"]),
            Paragraph(f"Goal: {goal}", styles["body"]),
        ]
        for r in resources:
            week_block.append(Paragraph(f"•  {r}", styles["bullet"]))
        week_block.append(Spacer(1, 2*mm))

        items.extend(week_block)

    return items
